### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by waydeg** [pmakarov/testwing#1]
Hi, I saw this project contains an XML Parser class. Would it be okay for me to use this in a project to parse EDI files? Basically, what is the license for this code?

Thanks,
Wayde

**Comment by waydeg** [comment]
Sorry, I meant X12 parser.

**Comment by pmakarov** [comment]
Hi Wayde,
Unfortunately the code does not, in fact, parse X12. It is a misnomer. It
was meant to target segments of an x12 document and create a unique
identifier by which to search through other elated EDI files.

However, depending on your project requirements, I may have some
substantial code or platform recommendations to exactly parse EDI files.

Thanks!

**Comment by waydeg** [comment]
Ah, thanks. I am unable to find a php class out there to parse edi files in x12 format

Wayde
